"""Centralized configuration values for RF Presence Radar."""

# Runtime / Performance
UI_FPS = 30
CORE_TICK_RATE = 10
OBS_QUEUE_MAXSIZE = 256
SNAPSHOT_QUEUE_MAXSIZE = 1

# RSSI / Señal
RSSI_MIN = -100
RSSI_MAX = -20
RSSI_SMOOTHING = 0.5
RSSI_STALE_TIMEOUT = 5.0
RSSI_BANDS = [(-100, -80), (-79, -60), (-59, -40), (-39, -20)]
RADII_NORMALIZED = [1.0, 0.8, 0.55, 0.3]
TARGET_UPDATE_INTERVAL = 10  # seconds
TARGET_LOG_INTERVAL = 10  # seconds
TARGET_DEBUG_LOG = False
VIEW_NAMES = ("LIST", "FAR", "NEAR")

# Modos
ENABLE_WIFI = False
ENABLE_BLE = False
ENABLE_SIMULATOR = True

# Logging
LOG_LEVEL = "DEBUG"
TARGET_DEBUG_LOG = True
